title: Project Websites
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ect123/project-site-ghpages-jekyll-workshop\">View workshop content in GitHub</a>"
