title: Project Websites
remote_theme: UBC-Library-Research-Commons/rc_workshop_template
footer_content: "<a href=\"https://github.com/ect123/project-site-ghpages-jekyll-workshop\">View workshop content in GitHub</a>"
